apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: grupo2
  labels:
    app: grupo2
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
